# Generated by Django 4.2.23 on 2025-08-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssetClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GlidepathRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gt_retire_age", models.IntegerField()),
                ("lt_retire_age", models.IntegerField()),
            ],
            options={
                "ordering": ["gt_retire_age", "lt_retire_age"],
                "unique_together": {("gt_retire_age", "lt_retire_age")},
            },
        ),
        migrations.CreateModel(
            name="AssetCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="glidepath_app.assetclass",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "asset_class")},
            },
        ),
        migrations.CreateModel(
            name="ClassAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "asset_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glidepath_app.assetclass",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="class_allocations",
                        to="glidepath_app.glidepathrule",
                    ),
                ),
            ],
            options={
                "unique_together": {("rule", "asset_class")},
            },
        ),
        migrations.CreateModel(
            name="CategoryAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "asset_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="glidepath_app.assetcategory",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_allocations",
                        to="glidepath_app.glidepathrule",
                    ),
                ),
            ],
            options={
                "unique_together": {("rule", "asset_category")},
            },
        ),
    ]
