# Generated by Django 4.2.23 on 2025-08-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glidepath_app", "0002_default_asset_classes"),
    ]

    operations = [
        migrations.CreateModel(
            name="RuleSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="glidepathrule",
            options={"ordering": ["ruleset", "gt_retire_age", "lt_retire_age"]},
        ),
        migrations.AlterUniqueTogether(
            name="glidepathrule",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="glidepathrule",
            name="ruleset",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rules",
                to="glidepath_app.ruleset",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="glidepathrule",
            unique_together={("ruleset", "gt_retire_age", "lt_retire_age")},
        ),
    ]
