# Generated by Django 4.2.23 on 2025-11-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("glidepath_app", "0003_ruleset_alter_glidepathrule_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="APISettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "alpha_vantage_api_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "finnhub_api_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "polygon_api_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "eodhd_api_key",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True),
                ),
            ],
            options={
                "verbose_name": "API Settings",
                "verbose_name_plural": "API Settings",
            },
        ),
    ]
