# Generated by Django 4.2.23 on 2025-11-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glidepath_app", "0004_apisettings"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticker",
                    models.CharField(max_length=20, unique=True),
                ),
                (
                    "name",
                    models.CharField(max_length=200),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funds",
                        to="glidepath_app.assetcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["ticker"],
            },
        ),
    ]
