# Generated by Django 4.2.23 on 2025-11-08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("glidepath_app", "0005_fund"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="funds",
                to="glidepath_app.assetcategory",
            ),
        ),
    ]
