# Generated by Django 4.2.26 on 2025-11-08 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0006_make_fund_category_nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentityProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('type', models.IntegerField(choices=[(0, 'OAuth2/OIDC')], default=0)),
                ('redirect_url', models.URLField(blank=True)),
                ('auto_provision_users', models.BooleanField(default=False)),
                ('client_id', models.CharField(max_length=500)),
                ('client_secret', models.CharField(max_length=500)),
                ('authorization_url', models.URLField()),
                ('token_url', models.URLField()),
                ('identity_path', models.CharField(help_text='JSON path to user identity in provider response', max_length=200)),
                ('email_path', models.CharField(help_text='JSON path to email in provider response', max_length=200)),
                ('name_path', models.CharField(blank=True, help_text='JSON path to name in provider response', max_length=200)),
                ('scopes', models.CharField(help_text='Space-separated OAuth scopes', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('role', models.IntegerField(choices=[(0, 'Administrator'), (1, 'User')], default=1)),
                ('disabled', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, help_text='Only used for internal users', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identity_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='glidepath_app.identityprovider')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
    ]
