# Generated by Django 4.2.26 on 2025-11-09 00:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0007_identityprovider_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload_datetime', models.DateTimeField(auto_now_add=True)),
                ('file_datetime', models.CharField(help_text='Raw date/time string from CSV file', max_length=200)),
                ('upload_type', models.CharField(choices=[('fidelity', 'Fidelity')], max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('entry_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_uploads', to='glidepath_app.user')),
            ],
            options={
                'ordering': ['-upload_datetime'],
            },
        ),
        migrations.CreateModel(
            name='AccountPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=200)),
                ('symbol', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('last_price', models.CharField(blank=True, max_length=50)),
                ('last_price_change', models.CharField(blank=True, max_length=50)),
                ('current_value', models.CharField(blank=True, max_length=50)),
                ('todays_gain_loss_dollar', models.CharField(blank=True, max_length=50)),
                ('todays_gain_loss_percent', models.CharField(blank=True, max_length=50)),
                ('total_gain_loss_dollar', models.CharField(blank=True, max_length=50)),
                ('total_gain_loss_percent', models.CharField(blank=True, max_length=50)),
                ('percent_of_account', models.CharField(blank=True, max_length=50)),
                ('cost_basis_total', models.CharField(blank=True, max_length=50)),
                ('average_cost_basis', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='glidepath_app.accountupload')),
            ],
            options={
                'ordering': ['upload', 'account_number', 'symbol'],
            },
        ),
    ]
