# Generated by Django 4.2.26 on 2025-11-08 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0009_portfolio_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='ruleset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portfolios', to='glidepath_app.ruleset'),
        ),
    ]
