# Generated by Django 4.2.26 on 2025-11-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0010_portfolio_ruleset'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='retirement_age',
            field=models.IntegerField(blank=True, help_text='Target retirement age for allocation', null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='year_born',
            field=models.IntegerField(blank=True, help_text='Birth year for target allocation calculation', null=True),
        ),
    ]
