# Generated by Django 5.2.8 on 2025-11-14 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "glidepath_app",
            "0014_alter_accountupload_upload_type_assumptionupload_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="assumptionupload",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assumption_uploads",
                to="glidepath_app.user",
            ),
        ),
    ]
