# Generated by Django 4.2.26 on 2025-11-18 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0016_categoryassumptionmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('session_timeout_minutes', models.IntegerField(default=360, help_text='Session timeout in minutes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Session Settings',
                'verbose_name_plural': 'Session Settings',
            },
        ),
    ]
