# Generated by Django 4.2.26 on 2025-11-19 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0017_sessionsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='external_provider_id',
            field=models.CharField(blank=True, help_text='External user ID from OAuth provider (e.g., sub claim, username)', max_length=500),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('external_provider_id__gt', ''), ('identity_provider__isnull', False)), fields=('identity_provider', 'external_provider_id'), name='unique_provider_external_id'),
        ),
    ]
