# Generated by Django 4.2.26 on 2026-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0018_user_external_provider_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=50, unique=True)),
                ('price_source_url', models.URLField(blank=True)),
                ('price_scraper', models.CharField(blank=True, help_text="Scraper identifier dispatched by scraper_service (e.g. 'nysaves').", max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('last_price_refresh', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VirtualFund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=100)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('price_as_of', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='virtual_funds', to='glidepath_app.fundprovider')),
            ],
            options={
                'ordering': ['provider', 'name'],
                'unique_together': {('provider', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='accountupload',
            name='account_type',
            field=models.CharField(choices=[('retirement', 'Retirement'), ('education', 'Education / 529'), ('general', 'General')], default='retirement', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='account_type',
            field=models.CharField(choices=[('retirement', 'Retirement'), ('education', 'Education / 529'), ('general', 'General')], default='retirement', max_length=20),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='annual_contribution',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual savings contribution to this portfolio (also used by retirement projections)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='annual_withdrawal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed dollar amount withdrawn per year of school', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='college_duration_years',
            field=models.IntegerField(default=4, help_text='Number of years funds will be withdrawn for school'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='return_assumption',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual return assumption percentage used for projection (e.g. 6.00)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='years_to_enrollment',
            field=models.IntegerField(blank=True, help_text='Years until the student starts college (negative = already enrolled)', null=True),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='account_type',
            field=models.CharField(choices=[('retirement', 'Retirement'), ('education', 'Education / 529'), ('general', 'General')], default='retirement', help_text='Which kind of portfolio this rule set applies to. For education rule sets, the age-band fields are interpreted as years to enrollment.', max_length=20),
        ),
        migrations.AddField(
            model_name='ruleset',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accountupload',
            name='upload_type',
            field=models.CharField(choices=[('fidelity', 'Fidelity'), ('etrade', 'E-Trade'), ('nysaves', 'NY 529 (NYSaves)')], max_length=50),
        ),
        migrations.AddField(
            model_name='accountposition',
            name='virtual_fund',
            field=models.ForeignKey(blank=True, help_text='Set for virtual-fund (e.g. 529) positions; null for real-ticker positions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='positions', to='glidepath_app.virtualfund'),
        ),
        migrations.AddField(
            model_name='accountupload',
            name='fund_provider',
            field=models.ForeignKey(blank=True, help_text='Set for virtual-fund uploads (e.g. 529 plans).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='glidepath_app.fundprovider'),
        ),
        migrations.CreateModel(
            name='VirtualFundComposition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asset_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glidepath_app.assetcategory')),
                ('virtual_fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='glidepath_app.virtualfund')),
            ],
            options={
                'unique_together': {('virtual_fund', 'asset_category')},
            },
        ),
    ]
