# Generated by Django 4.2.30 on 2026-06-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0021_seed_example_education_ruleset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='years_to_enrollment',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='enrollment_age',
            field=models.IntegerField(blank=True, help_text="Age at which the student starts college (the glide path's year 0).", null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='year_born',
            field=models.IntegerField(blank=True, help_text="Birth year. Retirement: the saver's; education: the student's.", null=True),
        ),
    ]
