# Generated by Django 4.2.30 on 2026-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0023_reseed_example_education_ruleset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruleset',
            name='account_type',
            field=models.CharField(choices=[('retirement', 'Retirement'), ('education', 'Education / 529'), ('general', 'General')], default='retirement', help_text='Which kind of portfolio this rule set applies to. The age-band fields are years relative to the milestone (negative = before, 0 = the milestone, positive = after); for education the milestone is college enrollment.', max_length=20),
        ),
    ]
