# Generated by Django 4.2.30 on 2026-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0024_alter_ruleset_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='import_token',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Bearer token for the bookmarklet holdings-import endpoint (per user; rotatable).', max_length=64),
        ),
    ]
