# Generated by Django 4.2.30 on 2026-06-28 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glidepath_app', '0025_user_import_token'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('import_token__gt', '')), fields=('import_token',), name='unique_import_token'),
        ),
    ]
