from django.urls import path
from glidepath_app.views import (
    home,
    rules_view,
    funds_view,
    accounts_view,
    view_account_upload,
    delete_account_upload,
    portfolios_view,
    create_portfolio,
    edit_portfolio,
    delete_portfolio,
    download_portfolio_csv,
    modeling_view,
    settings_view,
    logout_view,
    export_rules,
    query_ticker,
    fund_detail,
    delete_fund,
    user_detail,
    delete_user,
    select_user,
    identity_provider_detail,
    delete_identity_provider,
    download_funds_csv,
    upload_funds_csv,
)

urlpatterns = [
    path('', home, name='home'),
    path('rules/', rules_view, name='rules'),
    path('funds/', funds_view, name='funds'),
    path('funds/detail/', fund_detail, name='fund_detail'),
    path('funds/delete/<int:fund_id>/', delete_fund, name='delete_fund'),
    path('accounts/', accounts_view, name='accounts'),
    path('accounts/upload/<uuid:upload_id>/', view_account_upload, name='view_account_upload'),
    path('accounts/upload/<uuid:upload_id>/delete/', delete_account_upload, name='delete_account_upload'),
    path('portfolios/', portfolios_view, name='portfolios'),
    path('portfolios/create/', create_portfolio, name='portfolio_create'),
    path('portfolios/<uuid:portfolio_id>/edit/', edit_portfolio, name='edit_portfolio'),
    path('portfolios/<uuid:portfolio_id>/delete/', delete_portfolio, name='delete_portfolio'),
    path('portfolios/<uuid:portfolio_id>/download/', download_portfolio_csv, name='download_portfolio_csv'),
    path('modeling/', modeling_view, name='modeling'),
    path('settings/', settings_view, name='settings'),
    path('settings/users/add/', user_detail, name='user_add'),
    path('settings/users/<uuid:user_id>/edit/', user_detail, name='user_edit'),
    path('settings/users/<uuid:user_id>/delete/', delete_user, name='user_delete'),
    path('settings/users/<uuid:user_id>/select/', select_user, name='select_user'),
    path('settings/identity-providers/add/', identity_provider_detail, name='identity_provider_add'),
    path('settings/identity-providers/<uuid:provider_id>/edit/', identity_provider_detail, name='identity_provider_edit'),
    path('settings/identity-providers/<uuid:provider_id>/delete/', delete_identity_provider, name='identity_provider_delete'),
    path('logout/', logout_view, name='logout'),
    path('export/', export_rules, name='export_rules'),
    path('api/query-ticker/', query_ticker, name='query_ticker'),
    path('settings/funds/download/', download_funds_csv, name='download_funds_csv'),
    path('settings/funds/upload/', upload_funds_csv, name='upload_funds_csv'),
]
